name: Manual Workflow with Conditional Execution

on:
  workflow_dispatch: # Manual trigger

jobs:
  check-first-workflow:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Setting the GitHub token for GitHub CLI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Check First Workflow Status
        id: check-status
        run: |
          first_workflow_name="Scheduled mat view"
          runs=$(gh run list --workflow "$first_workflow_name" --status in_progress --limit 1)
          if [[ -z "$runs" ]]
          then
            echo "is_running=false" >> $GITHUB_ENV
          else
            echo "is_running=true" >> $GITHUB_ENV

    outputs:
      is_running: ${{ steps.check-status.outputs.is_running }}

  run-manual-task:
    runs-on: ubuntu-latest
    needs: check-first-workflow
    if: ${{ needs['check-first-workflow'].outputs.is_running == 'false' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Task
        run: echo "Running manual workflow"
