name: schema generation

on:
  workflow_dispatch: # Manual trigger

jobs:
  check-first-workflow:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Setting the GitHub token for GitHub CLI
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Check First Workflow Status
        id: check-status
        run: |
          first_workflow_name="Scheduled mat view"
          runs=$(gh run list --workflow "$first_workflow_name" --status in_progress --limit 1)
          if [[ -z "$runs" ]]; then
            echo "::set-output name=is_running::false"
          else:
            echo "::set-output name=is_running::true"
  
  run-manual-task:
    runs-on: ubuntu-latest
    needs: check-first-workflow
    if: ${{ needs.check-first-workflow.outputs.is_first_workflow_running == 'false' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Task
        run: echo "Running manual workflow"
